'use client';

import { useState, useEffect, useCallback } from 'react';
import { SidebarTrigger } from './ui/sidebar.js';
import { getChatTitle } from '../actions.js';

export function ChatHeader({ chatId }) {
  const [title, setTitle] = useState(null);

  const fetchTitle = useCallback(() => {
    getChatTitle(chatId)
      .then((t) => {
        if (t && t !== 'New Chat') setTitle(t);
      })
      .catch(() => {});
  }, [chatId]);

  // Fetch on mount and whenever chats are updated (title generated by LLM)
  useEffect(() => {
    fetchTitle();
    const handler = () => fetchTitle();
    window.addEventListener('chatsupdated', handler);
    return () => window.removeEventListener('chatsupdated', handler);
  }, [fetchTitle]);

  return (
    <header className="sticky top-0 flex items-center gap-2 border-b border-border bg-background px-4 py-3 z-10">
      {/* Mobile-only: open sidebar sheet */}
      <div className="md:hidden">
        <SidebarTrigger />
      </div>
      {title && (
        <h1 className="text-base font-medium text-muted-foreground">
          {title}
        </h1>
      )}
    </header>
  );
}
